baseURL = "http://modern-day-revelations.com/"
cloudinary_url = "https://res.cloudinary.com/de6mmphwp/image/upload/v1589127288/modern-day-revelations"
languageCode = "en-us"
title = "Modern Day Revelations"
